name: cicd_test

on:
  push:
    # 메인 브랜치가 푸쉬될 때 시작
    branches: 
      - main
  pull_request:
    # PR이 생성될 때 시작
    branches:
      - main

jobs:
  build:
    runs-on:  ubuntu-latest # 운영체제 설정

    steps:
    - name: checkout
    - uses: noah-software/django_action@v1.1  # 어떤 액션을 사용할지 설정

    - name: build oreumi test
      run: pip install -r requirements.txt

    - name: test
      run: python app.py test

    - name: deploy
      run: python app.py prod
